pagopa/selfcare-commons

base/src/main/java/it/pagopa/selfcare/commons/base/config/PerformanceLoggingConfig.java, base/src/main/resources/config/performance.properties, base/src/main/resources/logback-spring.xml, web/src/main/java/it/pagopa/selfcare/commons/web/config/BaseWebConfig.java, web/src/main/java/it/pagopa/selfcare/commons/web/config/SecurityConfig.java, web/src/main/java/it/pagopa/selfcare/commons/web/interceptor/LogRequestInterceptor.java, web/src/main/java/it/pagopa/selfcare/commons/web/security/JwtAuthenticationFilter.java, web/src/test/java/it/pagopa/selfcare/commons/web/interceptor/LogRequestInterceptorTest.java, web/src/test/java/it/pagopa/selfcare/commons/web/security/JwtAuthenticationFilterTest.java
- change log pattern
- add UID inside MDC
- add log interceptor in order to set MDC (UID)
- add performance logger (can be enabled via env var)
=> improve logging

base/pom.xml, base/src/main/java/it/pagopa/selfcare/commons/base/utils/Env.java, base/src/main/java/it/pagopa/selfcare/commons/base/utils/InstitutionPaSubunitType.java, base/src/main/java/it/pagopa/selfcare/commons/base/utils/Origin.java, base/src/main/java/it/pagopa/selfcare/commons/base/utils/PricingPlan.java, base/src/main/java/it/pagopa/selfcare/commons/base/utils/ProductId.java, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
added enum Origin, ProductId, InstitutionPaSubunitType, Env, PricingPlan and set version from 2.4.7 to 2.4.8
=> [SELC - 3100] added enum  and updated version

base/src/main/java/it/pagopa/selfcare/commons/base/utils/InstitutionType.java
Added new institutionType AS in enum InstitutionType
institutionType AS was added because SelfCare needs to allow onboarding to this new type of institution
AS: Assicurazioni
=> [SELC - 3218] feat: added new institutionType AS

base/pom.xml, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
updated common version from 2.4.8 to 2.4.9
=> [SELC 3218] feat: updated common version from 2.4.8 to 2.4.9

base/pom.xml, base/src/main/java/it/pagopa/selfcare/commons/base/utils/Origin.java, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/pom.xml, web/pom.xml
Added IVASS into eum Origin 
With new institution type AS, it has been necessary to add also new registry with Origin equals to IVASS.
=> [SELC-3300] feat: added IVASS in enum Origin

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml, pom.xml
- updated starter-parent version from 0.0.2 to 0.0.3 for jdk 17 update
- updated pipelines from 1.11 to 1.17
These updates are necessary as there is a need to upgrade to java 17
=> [SELC-3371] feat: update to jdk 17

infra/terraform-modules/github_repository_settings/locals.tf
Repository variables are renamed with ARM prefix
Consistent naming with environment variables used by terraform. 
Tentative to reuse same env vars without redefining them everytime
=> Rename variables and secrets to use ARM as prefix

.github/workflows/call_code_review_docker.yml, .github/workflows/call_code_review_spring.yml, .github/workflows/call_pr_labeler.yml, .github/workflows/call_pr_validation.yml, .github/workflows/call_release_docker.yml, .github/workflows/composite_create_release_branch.yml
* Added workflow template for release docker image
* Added  workflow template for pr with java application
* Added workflow for creare branch release
=> [EC-149] Added template git hub workflows

.github/workflows/call_code_review_docker.yml, .github/workflows/call_code_review_spring.yml, .github/workflows/call_release_docker.yml
Added reference of selfcare-onboarding repo on settings.xml when
* Build docker image workflow
* Launch code review spring workflow
Some repo need to retrieve onboarding-sdk
=> Authentication for retrieve onboarding-sdk

github-actions-template/create-release/README.md, github-actions-template/create-release/action.yml
GitHub Action that automates the process of creating release branches for a repository, updating version numbers, and creating releases with release notes.
=> chore: create release action

github-actions-template/create-release/README.md, github-actions-template/create-release/action.yml, github-actions-template/promote-release/README.md, github-actions-template/promote-release/action.yml
* Added GitHub Action automates the process of creating release branches for a repository, updating version numbers, and creating releases with release notes.
* Added new_branch_name output to create_release action
=> chore: Added promote release action

infra/terraform-modules/container_app_microservice/locals.tf, infra/terraform-modules/container_app_microservice/variables.tf
=> Added resource_group_name as variable to Container App module

infra/terraform-modules/container_app_microservice/variables.tf
=> Added initial delay to probes on Container App module

github-actions-template/swagger-detect-conflict-quarkus/action.yml, github-actions-template/swagger-detect-conflict-spring/action.yml
* Added Optic to the GitHub Actions workflow to monitor and detect breaking changes in our Swagger API specifications.
* Configured Optic to utilize our existing OpenAPI specifications for precise validation.
This pull request introduces a modification to our GitHub Actions workflow by integrating Optic for improved Swagger conflict detection. Optic is a tool that enables us to detect breaking changes by utilizing OpenAPI specifications. Additionally, it allows us to set and enforce a series of rules regarding how APIs are defined, ensuring that these rules are adhered to consistently.
=> [SELC-5008] Integrate Optic for Enhanced Swagger Conflict Detection in GitHub Actions

.github/workflows/call_release_docker.yml
* Added new step on release_docker workflow
* New step upload a file on selc<env>checkoutsa storage
This PR introduce a new step on release docker microservice for uploading the openapi.json on azure storage. It is needed for implementing an r[elease API process automated](https://pagopa.atlassian.net/wiki/spaces/SCP/pages/1084883169/Area+Riservata+API+-+Processo+automatico+di+validazione+e+rilascio+REST+API)
=> [SELC-5009] Added upload openapi.json on azure storage for automation API process

.github/workflows/call_release_docker.yml
=> [SELC-5009] fix: add overwrite on upload openapi

base/pom.xml, base/src/main/java/it/pagopa/selfcare/commons/base/security/PartyRole.java, base/src/main/java/it/pagopa/selfcare/commons/base/security/SelfCareAuthority.java, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
- added ADMIN_EA PartyRole
- added ADMIN_EA SelfCareAuthority
- increased pom version from 2.5.1 to 2.5.2
=> [SELC-5059] feat: added ADMIN_EA as PartyRole and SelfCareAuthority

infra/terraform-modules/github_repository_settings/github_branch_rules.tf, infra/terraform-modules/github_repository_settings/github_environments_cd.tf
Avoid to approve multiple time the release workflow. We mantain reviewers only on uat-ci
=> Remove reviewers from uat-cd

infra/terraform-modules/github_repository_settings/github_environments_cd.tf
Avoid to approve multiple time the release workflow. We mantain reviewers only on prod-ci
=> Remove reviewers from prod-cd

base/pom.xml, base/src/main/java/it/pagopa/selfcare/commons/base/utils/InstitutionType.java, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
=> [SELC-5407] feat: added new institution type PRV

github-actions-template/swagger-detect-conflict-quarkus/action.yml, github-actions-template/swagger-detect-conflict-spring/action.yml, optic.yml
* Add optic.yml file
* Add step to download the file in order to enable check ruleset
=> feat: Added check Linter on swagger detect OpenAPI

optic.yml
Add some descriptions about rule present on optic.yml file
=> chore: Optic.yml documentation improvements

.github/workflows/call_release_cdn.yml
Added new action for CDN deploy, useful for frontend functions.
Is necessary a new action for deploy CDN, will be used from all the frontend functions.
=> [SELC-5477] Azure DevOps pipelines migrated into GitHub Actions

.github/workflows/env/fe_dev.env, .github/workflows/env/fe_dev_pnpg.env, .github/workflows/env/fe_prod.env, .github/workflows/env/fe_prod_pnpg.env, .github/workflows/env/fe_uat.env, .github/workflows/env/fe_uat_pnpg.env
feat: Removed unused env variable + changed some values
In order to not handle unused environment variables and make the value of one of them correct
=> feat: Removed unused env variable + changed some values

infra/terraform-modules/github_repository_settings/data.tf, infra/terraform-modules/github_repository_settings/locals.tf
=> Added Github PATH token to gh repository module

base/pom.xml, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml, web/src/main/java/it/pagopa/selfcare/commons/web/security/JwtAuthenticationProvider.java, web/src/main/java/it/pagopa/selfcare/commons/web/security/JwtService.java, web/src/main/java/it/pagopa/selfcare/commons/web/security/K8sJwtAuthenticationStrategy.java, web/src/main/java/it/pagopa/selfcare/commons/web/security/SpidJwtAuthenticationStrategy.java
- remove log with authentication token
- remove log with authentication result (name, surname, taxCode)
- remove log with claims (name, surname, taxCode)
- add log with authenticated userId
- upgrade commons version from 2.5.3 to 2.5.4
This change is required to prevent the logging of sensitive data, ensuring compliance with security and privacy best practices.
It was tested locally
=> [SELC-5884] chore: remove and modify logs to avoid logging authentication data

base/pom.xml, base/src/main/java/it/pagopa/selfcare/commons/base/utils/InstitutionType.java, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
=> [SELC-5513] feat: added institutionType GPU

.github/workflows/env/fe_dev.env, .github/workflows/env/fe_dev_pnpg.env, .github/workflows/env/fe_prod.env, .github/workflows/env/fe_prod_pnpg.env, .github/workflows/env/fe_uat.env, .github/workflows/env/fe_uat_pnpg.env, README.md
add env var to handle admin max count for selfcare
add env var to handle admin max count for pnpg
To disable add admin in the users section if the number of admins reached the max.
=> feat: add env var for max count of admin

base/pom.xml, base/src/main/java/it/pagopa/selfcare/commons/base/security/PartyRole.java, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
- add new PartyRole ADMIN_EA_IO
- upgrade commons version from 2.5.5 to 2.5.6
=> [SELC-6372] feat: add new PartyRole ADMIN_EA_IO

.github/workflows/env/fe_dev.env, .github/workflows/env/fe_dev_pnpg.env, .github/workflows/env/fe_prod.env, .github/workflows/env/fe_prod_pnpg.env, .github/workflows/env/fe_uat.env, .github/workflows/env/fe_uat_pnpg.env
Feat: Upadated pnpg env variable for email assistance
Updated pnpg env variable for email assistance to differentiate the value assumed by the client mail for the pnpg web portal with the expected address pre-filled. instead it's redirected to the selfcare web portal with his value pre-filled.
=> Feat: Upadated pnpg env variable for email assistance

base/pom.xml, base/src/main/java/it/pagopa/selfcare/commons/base/security/PartyRole.java, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
-remove role ADMIN_EA_IO
- update version to 2.5.7
=> [SELC-6457] fix: remove role ADMIN_EA_IO and update version

.github/workflows/env/fe_dev.env, .github/workflows/env/fe_dev_pnpg.env, .github/workflows/env/fe_prod.env, .github/workflows/env/fe_prod_pnpg.env, .github/workflows/env/fe_uat.env, .github/workflows/env/fe_uat_pnpg.env
add new env var for all enviroments.
To release in prod the frontends with the admin limit feature disabled
=> [SELC-6474] feat: add feature flag for admin limit

base/pom.xml, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml, web/src/main/java/it/pagopa/selfcare/commons/web/config/SecurityConfig.java
Updated pom references and spring security config for csrf
=> [SELC-5820] fix: update pom references

base/pom.xml, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml, web/src/main/java/it/pagopa/selfcare/commons/web/config/SecurityConfig.java, web/src/main/java/it/pagopa/selfcare/commons/web/security/JwtAuthenticationFilter.java, web/src/main/java/it/pagopa/selfcare/commons/web/security/K8sJwtAuthenticationStrategy.java
fixed exclusions for swagger endpoints
In order to avoid the check of authentication for swagger endpoints, a new bean has been configured into WebSecurityConfig class
=> [SELC-5801] fix: fixed exclusions for swagger endpoints

.github/workflows/env/fe_dev.env, .github/workflows/env/fe_dev_pnpg.env, .github/workflows/env/fe_prod.env, .github/workflows/env/fe_prod_pnpg.env, .github/workflows/env/fe_uat.env, .github/workflows/env/fe_uat_pnpg.env
Add env REACT_APP_OI_BASE_URL 
Add env REACT_APP_CLIENT_ID
Ad env vars for integration with OneIdentity
=> [SELC-6680] feature: add env vars for CLIENT_ID e OI_BASE_URL

github-actions-template/swagger-detect-conflict-spring/action.yml
Updated mvn action
After upgrading to spring version, it is necessary to rewrite the action that is executed by maven to generate the api-docs
The modification is backward-compatible with earlier versions of spring boot
=> fix: Swagger Detect Conflict and Update with Spring

.github/workflows/call_code_review_docker.yml, .github/workflows/call_code_review_spring.yml, .github/workflows/call_pr_labeler.yml, .github/workflows/call_pr_validation.yml, .github/workflows/call_release_docker.yml
=> feat: updated ubuntu version

base/pom.xml, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
=> [SELC-6802] feat: update common version to set ubuntu version to 24

.github/workflows/env/fe_dev.env, .github/workflows/env/fe_dev_pnpg.env, .github/workflows/env/fe_prod.env, .github/workflows/env/fe_prod_pnpg.env, .github/workflows/env/fe_uat.env, .github/workflows/env/fe_uat_pnpg.env
Add env var for selfcare and Pnpg
To be used by the FE to call the api oidc/exchange
=> [SELC-6807] feat: Add env var auth baseUrl

.github/workflows/env/fe_dev.env, .github/workflows/env/fe_uat.env
=> [SELC-6685] Add one identity client id and base url

base/pom.xml, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
Updated references to starter parent
=> Updated references to starter parent

.github/workflows/env/fe_prod.env
Add selfcare prod client id 
add selfcare prod oi base url
=> Add env var for client Id and oi base url

.github/workflows/env/fe_dev.env, .github/workflows/env/fe_prod.env, .github/workflows/env/fe_uat.env
Add env var  REACT_APP_SHOW_DOCUMENTS for selfcare 
Hide documents section in prod until missing contract issue is fixed.
=> [SELC-7075] feat: Add env var to handle documents section visibility

.github/workflows/call_release_docker.yml, base/pom.xml, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml
- Added arg REPO_SELFCARE in call_release_docker.yml
- Update pom.xml version
Fixes release workflow failures and enables successful builds by resolving cucumber-sdk dependency
=> [SELC-7138] fix: add REPO_SELFCARE in call_release_docker.yml and update version

.github/workflows/env/fe_dev_pnpg.env
update oneTrust baseUrl for dev
update oneTrust baseUrl for dev
=> update oneTrust baseUrl

base/pom.xml, connector/pom.xml, connector/rest/pom.xml, connector/soap/aruba-sign/pom.xml, connector/soap/pom.xml, connector/soap/utils/pom.xml, infra/terraform-modules/container_app_microservice/container_app.tf, infra/terraform-modules/container_app_microservice/variables.tf, pom.xml, utils/crypto/pom.xml, utils/pom.xml, web/pom.xml, web/src/main/java/it/pagopa/selfcare/commons/web/config/SecurityConfig.java
Modified SecurityConfig.java  adding  "/dapr/**" to AUTH_WHITELIST.
This pull request updates the security configuration to add a new endpoint to the authentication whitelist. The purpose of this change is to expose a new public-facing API path that can be accessed without requiring an authentication token.
The newly whitelisted path, /dapr/**, is needed for a integration with a DAPR sidecar service.
This change ensures that while the new endpoint is publicly accessible, all other existing endpoints remain protected and require proper authentication.
=> [SELC-7550] feat: Add new path to authentication whitelist

github-actions-template/swagger-detect-conflict-quarkus/action.yml
=> fix: updated swagger detect conflict action
